const usecartTexts = () => {

    const cartVibes = [
        "Hungry already? 🍔",
        "Cart feels lonely 🛒",
        "No bites yet 😶",
        "Feed the cart 🍴",
        "Add yummy stuff 😋",
        "Nothing cooking 👀",
        "Cravings pending 🍕",
        "Tummy’s waiting 🤤",
        "Plate is empty 🍽️",
        "Snack time? 🍪",
        "Foodie vibes 🍟",
        "Add some love 💕",
        "Where’s the feast? 🍖",
        "Cart’s on diet 🥦",
        "Hungry vibes 🔥",
        "Add some spice 🌶️",
        "Still starving? 😵",
        "Dish it up 🥳",
        "Need flavors 🍣",
        "Empty & sad 😔",
        "Cravings empty 🍩",
        "No flavor yet 🥱",
        "Cart’s starving 🥵",
        "Add taste fast ⚡",
        "Fill it up 💨",
        "Hungry mood 🍣",
        "Snack attack! 🍿",
        "Food missing 😭",
        "Need munchies 🤭",
        "Where’s dinner? 🍲",
        "Add some crunch 🍽️",
        "Crave unlocked 🔑",
        "Empty plate 😮‍💨",
        "Food vibes only 🍷",
        "Cart’s hollow 😵‍💫",
        "Bring the feast 🎉",
        "Order magic ✨",
        "Need treats 🍪",
        "Start munching 😍",
        "Crave mode 🔥",
        "Cart’s craving 🤤",
        "Zero bites 🥨",
        "Food please 🙏",
        "Taste missing 😕",
        "Always moody? 😏",
        "Why so empty? 🤔",
        "Snack vibes 🌮",
        "Meal time? 🍝",
        "Hungry cart 😢",
        "Add your dish 🥘",
        "Flavorless cart 🍞"
    ];

    const cartTaglines = [
        "Fill your cart with tasty magic",
        "Start adding bites that make you smile",
        "Your cravings deserve a place here",
        "Stack up your favorites, no waiting",
        "Turn hunger into happiness, add now",
        "Cart’s ready for your foodie vibes",
        "Pick something delicious, don’t be shy",
        "Hungry? Let’s fix that real quick",
        "Every feast begins with one click",
        "Load up flavors, empty no more",
        "Good food = good mood, start now",
        "Add tasty stuff, make the cart happy",
        "No joy in emptiness, add flavor",
        "Make it yours, add your cravings",
        "One bite away from happiness 🍔",
        "Cart’s calling, answer with food",
        "Why wait? Add your favorites today",
        "Let’s spice things up, add items",
        "Your plate’s waiting, fill it here",
        "Cart feels sad, cheer it with food",
        "Cravings knocking, open the cart now",
        "Don’t stay hungry, add some love",
        "Cart’s empty, flavor’s waiting for you",
        "Add a little spice to your life",
        "Your foodie journey starts right here",
        "Empty carts don’t taste good, fill it",
        "Stack some happiness inside your cart",
        "Make your cravings proud, add items",
        "No feast without a cart full",
        "Cart’s sad, bring joy with bites",
        "Good flavors are just one click away",
        "Turn that hunger into tasty moments",
        "Add your favorites, skip the waiting",
        "Fill it with joy, fill with food",
        "Hungry hearts need a happy cart",
        "Pick something fresh, fuel your vibe",
        "Empty carts never make full hearts",
        "Cravings unlocked, time to add more",
        "Treat yourself, happiness starts with food",
        "A tasty journey starts with one dish",
        "Don’t starve the cart, feed it now",
        "Food happiness is only one tap away",
        "Cart’s waiting for your flavor touch",
        "Start adding delicious bites to your cart",
        "Add bites that brighten your mood",
        "No joy in empty carts, add food",
        "Fuel up your hunger, start here",
        "Every craving deserves a place inside",
        "Your plate wants company, add items",
        "Cart’s ready, waiting for your favorites",
        "Why scroll hungry? Add your picks"
    ];

    const orderPlacedVibes = [
        "Order placed successfully 🎉",
        "Your order is confirmed ✅",
        "Boom! Order locked in 🚀",
        "Food on its way 🍔",
        "Yay! Order confirmed 🥳",
        "Your feast is secured 🍕",
        "Order confirmed, get ready 🍟",
        "It’s cooking now 🍳",
        "Order locked, sit back 🍜",
        "Your cravings are on track 📦",
        "Done! Order placed 🍝",
        "Hungry vibes incoming 🍱",
        "Your meal is secured 🥘",
        "Order confirmed, stay hungry 🔥",
        "You’re all set 🥂",
        "Order success, foodie 🥗",
        "Get ready to munch 🍩",
        "Yum is on the way 🍲",
        "Order complete, smile big 😋",
        "Your treat is confirmed 🍫",
        "Meal placed, happiness loaded 💯",
        "Order is all set 🎊",
        "Cravings secured 🥪",
        "Cart checked out, done 🛒",
        "Your bites are booked 🍪",
        "Confirmed! Feast time 🍗",
        "Order’s cooking up 🍤",
        "Food vibes secured 🥟",
        "Meal confirmed, sit tight 🥞",
        "Order done, get ready 🥯",
        "Order placed, relax now 🛋️",
        "Good news, it’s confirmed 📢",
        "Your hunger is handled 🍴",
        "Order locked, chef’s on it 👨‍🍳",
        "Food fix incoming 🍹",
        "Your belly’s next stop 🍛",
        "Order ready to roll 🚴",
        "Meal’s on the move 📦",
        "Confirmed and cooking 🍤",
        "Order success, cheers 🥂",
        "Dish locked, stay tuned 🍲",
        "Confirmed, taste buds happy 🤩",
        "Your bites are secured 🥨",
        "Kitchen’s got it covered 🍳",
        "Done deal, foodie win 🏆",
        "Order active, stay cozy 🧃",
        "Meal confirmed, countdown starts ⏳",
        "Order loaded, flavor coming 🌮",
        "Food journey begins 🚚",
        "Your munchies are confirmed 🥟"
    ];

    const thankYouVibes = [
        "Thanks for shopping with us",
        "We appreciate your order",
        "Thanks for being here",
        "Your support means a lot",
        "Grateful for your purchase",
        "Thanks for choosing us",
        "Always happy to serve you",
        "Big thanks for shopping",
        "Glad you shopped with us",
        "Thanks for trusting us",
        "Your choice matters to us",
        "Thanks for your support",
        "You made our day",
        "Thanks for your order",
        "Happy to have you here",
        "Thanks for shopping today",
        "Appreciate your trust",
        "Thanks for picking us",
        "We value your choice",
        "Thanks for staying with us",
        "Thanks for shopping again",
        "Your support counts",
        "Thank you, always",
        "We appreciate your trust",
        "Thanks for believing in us",
        "Always thankful for you",
        "Thanks for the love",
        "You’re the reason we grow",
        "Thanks for your loyalty",
        "Your order means a lot",
        "Thanks for being part of us",
        "We’re grateful for you",
        "Thanks for coming through",
        "Your support keeps us going",
        "Thanks for stopping by",
        "We’re glad you chose us",
        "Thank you kindly",
        "Always grateful for shoppers like you",
        "Thanks for every order",
        "Your support fuels us",
        "Thanks for your confidence",
        "We value your support",
        "Thanks, it means the world",
        "Your trust is our reward",
        "Thanks for sharing your trust",
        "Always here for you",
        "We appreciate you deeply",
        "Thanks for standing with us",
        "Thank you for being amazing",
        "Forever grateful for you"
    ];

    return (
        [cartVibes, cartTaglines, orderPlacedVibes, thankYouVibes]
    )
}


export default usecartTexts;